/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrendBoostRouteImport } from './routes/trend-boost'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PromptsRouteImport } from './routes/prompts'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as ModelosRouteImport } from './routes/modelos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndicacaoRouteImport } from './routes/indicacao'
import { Route as FerramentasRouteImport } from './routes/ferramentas'
import { Route as EstudioRouteImport } from './routes/estudio'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CriarAvatarRouteImport } from './routes/criar-avatar'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AvataresRouteImport } from './routes/avatares'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrendBoostIndexRouteImport } from './routes/trend-boost.index'
import { Route as ModelosIndexRouteImport } from './routes/modelos.index'
import { Route as EstudioIndexRouteImport } from './routes/estudio.index'
import { Route as TrendBoostTemplateRouteImport } from './routes/trend-boost.$template'
import { Route as ModelosUsarRouteImport } from './routes/modelos.usar'
import { Route as GerarModeloViralRouteImport } from './routes/gerar.modelo-viral'
import { Route as EstudioFormatRouteImport } from './routes/estudio.$format'

const TrendBoostRoute = TrendBoostRouteImport.update({
  id: '/trend-boost',
  path: '/trend-boost',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptsRoute = PromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelosRoute = ModelosRouteImport.update({
  id: '/modelos',
  path: '/modelos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndicacaoRoute = IndicacaoRouteImport.update({
  id: '/indicacao',
  path: '/indicacao',
  getParentRoute: () => rootRouteImport,
} as any)
const FerramentasRoute = FerramentasRouteImport.update({
  id: '/ferramentas',
  path: '/ferramentas',
  getParentRoute: () => rootRouteImport,
} as any)
const EstudioRoute = EstudioRouteImport.update({
  id: '/estudio',
  path: '/estudio',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CriarAvatarRoute = CriarAvatarRouteImport.update({
  id: '/criar-avatar',
  path: '/criar-avatar',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AvataresRoute = AvataresRouteImport.update({
  id: '/avatares',
  path: '/avatares',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendBoostIndexRoute = TrendBoostIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TrendBoostRoute,
} as any)
const ModelosIndexRoute = ModelosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ModelosRoute,
} as any)
const EstudioIndexRoute = EstudioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EstudioRoute,
} as any)
const TrendBoostTemplateRoute = TrendBoostTemplateRouteImport.update({
  id: '/$template',
  path: '/$template',
  getParentRoute: () => TrendBoostRoute,
} as any)
const ModelosUsarRoute = ModelosUsarRouteImport.update({
  id: '/usar',
  path: '/usar',
  getParentRoute: () => ModelosRoute,
} as any)
const GerarModeloViralRoute = GerarModeloViralRouteImport.update({
  id: '/gerar/modelo-viral',
  path: '/gerar/modelo-viral',
  getParentRoute: () => rootRouteImport,
} as any)
const EstudioFormatRoute = EstudioFormatRouteImport.update({
  id: '/$format',
  path: '/$format',
  getParentRoute: () => EstudioRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/avatares': typeof AvataresRoute
  '/cadastro': typeof CadastroRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/criar-avatar': typeof CriarAvatarRoute
  '/dashboard': typeof DashboardRoute
  '/estudio': typeof EstudioRouteWithChildren
  '/ferramentas': typeof FerramentasRoute
  '/indicacao': typeof IndicacaoRoute
  '/login': typeof LoginRoute
  '/modelos': typeof ModelosRouteWithChildren
  '/perfil': typeof PerfilRoute
  '/produtos': typeof ProdutosRoute
  '/prompts': typeof PromptsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trend-boost': typeof TrendBoostRouteWithChildren
  '/estudio/$format': typeof EstudioFormatRoute
  '/gerar/modelo-viral': typeof GerarModeloViralRoute
  '/modelos/usar': typeof ModelosUsarRoute
  '/trend-boost/$template': typeof TrendBoostTemplateRoute
  '/estudio/': typeof EstudioIndexRoute
  '/modelos/': typeof ModelosIndexRoute
  '/trend-boost/': typeof TrendBoostIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/avatares': typeof AvataresRoute
  '/cadastro': typeof CadastroRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/criar-avatar': typeof CriarAvatarRoute
  '/dashboard': typeof DashboardRoute
  '/ferramentas': typeof FerramentasRoute
  '/indicacao': typeof IndicacaoRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/produtos': typeof ProdutosRoute
  '/prompts': typeof PromptsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/estudio/$format': typeof EstudioFormatRoute
  '/gerar/modelo-viral': typeof GerarModeloViralRoute
  '/modelos/usar': typeof ModelosUsarRoute
  '/trend-boost/$template': typeof TrendBoostTemplateRoute
  '/estudio': typeof EstudioIndexRoute
  '/modelos': typeof ModelosIndexRoute
  '/trend-boost': typeof TrendBoostIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/avatares': typeof AvataresRoute
  '/cadastro': typeof CadastroRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/criar-avatar': typeof CriarAvatarRoute
  '/dashboard': typeof DashboardRoute
  '/estudio': typeof EstudioRouteWithChildren
  '/ferramentas': typeof FerramentasRoute
  '/indicacao': typeof IndicacaoRoute
  '/login': typeof LoginRoute
  '/modelos': typeof ModelosRouteWithChildren
  '/perfil': typeof PerfilRoute
  '/produtos': typeof ProdutosRoute
  '/prompts': typeof PromptsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trend-boost': typeof TrendBoostRouteWithChildren
  '/estudio/$format': typeof EstudioFormatRoute
  '/gerar/modelo-viral': typeof GerarModeloViralRoute
  '/modelos/usar': typeof ModelosUsarRoute
  '/trend-boost/$template': typeof TrendBoostTemplateRoute
  '/estudio/': typeof EstudioIndexRoute
  '/modelos/': typeof ModelosIndexRoute
  '/trend-boost/': typeof TrendBoostIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/avatares'
    | '/cadastro'
    | '/configuracoes'
    | '/criar-avatar'
    | '/dashboard'
    | '/estudio'
    | '/ferramentas'
    | '/indicacao'
    | '/login'
    | '/modelos'
    | '/perfil'
    | '/produtos'
    | '/prompts'
    | '/sitemap.xml'
    | '/trend-boost'
    | '/estudio/$format'
    | '/gerar/modelo-viral'
    | '/modelos/usar'
    | '/trend-boost/$template'
    | '/estudio/'
    | '/modelos/'
    | '/trend-boost/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/avatares'
    | '/cadastro'
    | '/configuracoes'
    | '/criar-avatar'
    | '/dashboard'
    | '/ferramentas'
    | '/indicacao'
    | '/login'
    | '/perfil'
    | '/produtos'
    | '/prompts'
    | '/sitemap.xml'
    | '/estudio/$format'
    | '/gerar/modelo-viral'
    | '/modelos/usar'
    | '/trend-boost/$template'
    | '/estudio'
    | '/modelos'
    | '/trend-boost'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/avatares'
    | '/cadastro'
    | '/configuracoes'
    | '/criar-avatar'
    | '/dashboard'
    | '/estudio'
    | '/ferramentas'
    | '/indicacao'
    | '/login'
    | '/modelos'
    | '/perfil'
    | '/produtos'
    | '/prompts'
    | '/sitemap.xml'
    | '/trend-boost'
    | '/estudio/$format'
    | '/gerar/modelo-viral'
    | '/modelos/usar'
    | '/trend-boost/$template'
    | '/estudio/'
    | '/modelos/'
    | '/trend-boost/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AvataresRoute: typeof AvataresRoute
  CadastroRoute: typeof CadastroRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  CriarAvatarRoute: typeof CriarAvatarRoute
  DashboardRoute: typeof DashboardRoute
  EstudioRoute: typeof EstudioRouteWithChildren
  FerramentasRoute: typeof FerramentasRoute
  IndicacaoRoute: typeof IndicacaoRoute
  LoginRoute: typeof LoginRoute
  ModelosRoute: typeof ModelosRouteWithChildren
  PerfilRoute: typeof PerfilRoute
  ProdutosRoute: typeof ProdutosRoute
  PromptsRoute: typeof PromptsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TrendBoostRoute: typeof TrendBoostRouteWithChildren
  GerarModeloViralRoute: typeof GerarModeloViralRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trend-boost': {
      id: '/trend-boost'
      path: '/trend-boost'
      fullPath: '/trend-boost'
      preLoaderRoute: typeof TrendBoostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompts': {
      id: '/prompts'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof PromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modelos': {
      id: '/modelos'
      path: '/modelos'
      fullPath: '/modelos'
      preLoaderRoute: typeof ModelosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indicacao': {
      id: '/indicacao'
      path: '/indicacao'
      fullPath: '/indicacao'
      preLoaderRoute: typeof IndicacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ferramentas': {
      id: '/ferramentas'
      path: '/ferramentas'
      fullPath: '/ferramentas'
      preLoaderRoute: typeof FerramentasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estudio': {
      id: '/estudio'
      path: '/estudio'
      fullPath: '/estudio'
      preLoaderRoute: typeof EstudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criar-avatar': {
      id: '/criar-avatar'
      path: '/criar-avatar'
      fullPath: '/criar-avatar'
      preLoaderRoute: typeof CriarAvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avatares': {
      id: '/avatares'
      path: '/avatares'
      fullPath: '/avatares'
      preLoaderRoute: typeof AvataresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trend-boost/': {
      id: '/trend-boost/'
      path: '/'
      fullPath: '/trend-boost/'
      preLoaderRoute: typeof TrendBoostIndexRouteImport
      parentRoute: typeof TrendBoostRoute
    }
    '/modelos/': {
      id: '/modelos/'
      path: '/'
      fullPath: '/modelos/'
      preLoaderRoute: typeof ModelosIndexRouteImport
      parentRoute: typeof ModelosRoute
    }
    '/estudio/': {
      id: '/estudio/'
      path: '/'
      fullPath: '/estudio/'
      preLoaderRoute: typeof EstudioIndexRouteImport
      parentRoute: typeof EstudioRoute
    }
    '/trend-boost/$template': {
      id: '/trend-boost/$template'
      path: '/$template'
      fullPath: '/trend-boost/$template'
      preLoaderRoute: typeof TrendBoostTemplateRouteImport
      parentRoute: typeof TrendBoostRoute
    }
    '/modelos/usar': {
      id: '/modelos/usar'
      path: '/usar'
      fullPath: '/modelos/usar'
      preLoaderRoute: typeof ModelosUsarRouteImport
      parentRoute: typeof ModelosRoute
    }
    '/gerar/modelo-viral': {
      id: '/gerar/modelo-viral'
      path: '/gerar/modelo-viral'
      fullPath: '/gerar/modelo-viral'
      preLoaderRoute: typeof GerarModeloViralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estudio/$format': {
      id: '/estudio/$format'
      path: '/$format'
      fullPath: '/estudio/$format'
      preLoaderRoute: typeof EstudioFormatRouteImport
      parentRoute: typeof EstudioRoute
    }
  }
}

interface EstudioRouteChildren {
  EstudioFormatRoute: typeof EstudioFormatRoute
  EstudioIndexRoute: typeof EstudioIndexRoute
}

const EstudioRouteChildren: EstudioRouteChildren = {
  EstudioFormatRoute: EstudioFormatRoute,
  EstudioIndexRoute: EstudioIndexRoute,
}

const EstudioRouteWithChildren =
  EstudioRoute._addFileChildren(EstudioRouteChildren)

interface ModelosRouteChildren {
  ModelosUsarRoute: typeof ModelosUsarRoute
  ModelosIndexRoute: typeof ModelosIndexRoute
}

const ModelosRouteChildren: ModelosRouteChildren = {
  ModelosUsarRoute: ModelosUsarRoute,
  ModelosIndexRoute: ModelosIndexRoute,
}

const ModelosRouteWithChildren =
  ModelosRoute._addFileChildren(ModelosRouteChildren)

interface TrendBoostRouteChildren {
  TrendBoostTemplateRoute: typeof TrendBoostTemplateRoute
  TrendBoostIndexRoute: typeof TrendBoostIndexRoute
}

const TrendBoostRouteChildren: TrendBoostRouteChildren = {
  TrendBoostTemplateRoute: TrendBoostTemplateRoute,
  TrendBoostIndexRoute: TrendBoostIndexRoute,
}

const TrendBoostRouteWithChildren = TrendBoostRoute._addFileChildren(
  TrendBoostRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AvataresRoute: AvataresRoute,
  CadastroRoute: CadastroRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  CriarAvatarRoute: CriarAvatarRoute,
  DashboardRoute: DashboardRoute,
  EstudioRoute: EstudioRouteWithChildren,
  FerramentasRoute: FerramentasRoute,
  IndicacaoRoute: IndicacaoRoute,
  LoginRoute: LoginRoute,
  ModelosRoute: ModelosRouteWithChildren,
  PerfilRoute: PerfilRoute,
  ProdutosRoute: ProdutosRoute,
  PromptsRoute: PromptsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TrendBoostRoute: TrendBoostRouteWithChildren,
  GerarModeloViralRoute: GerarModeloViralRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
