/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrendBoostRouteImport } from './routes/trend-boost'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ReferralRouteImport } from './routes/referral'
import { Route as PromptsRouteImport } from './routes/prompts'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CreditsRouteImport } from './routes/credits'
import { Route as CreateFromScratchRouteImport } from './routes/create-from-scratch'
import { Route as CreateAvatarRouteImport } from './routes/create-avatar'
import { Route as AvatarsRouteImport } from './routes/avatars'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrendBoostIndexRouteImport } from './routes/trend-boost.index'
import { Route as TemplatesIndexRouteImport } from './routes/templates.index'
import { Route as StudioIndexRouteImport } from './routes/studio.index'
import { Route as CreateFromScratchIndexRouteImport } from './routes/create-from-scratch.index'
import { Route as TrendBoostTemplateRouteImport } from './routes/trend-boost.$template'
import { Route as TemplatesUseRouteImport } from './routes/templates.use'
import { Route as StudioFormatRouteImport } from './routes/studio.$format'
import { Route as GenerateViralTemplateRouteImport } from './routes/generate.viral-template'
import { Route as CreateFromScratchScenarioRouteImport } from './routes/create-from-scratch.scenario'
import { Route as CreateFromScratchPoseRouteImport } from './routes/create-from-scratch.pose'
import { Route as TrendBoostTemplateIndexRouteImport } from './routes/trend-boost.$template.index'
import { Route as TrendBoostTemplateCharacterIdRouteImport } from './routes/trend-boost.$template.$characterId'

const TrendBoostRoute = TrendBoostRouteImport.update({
  id: '/trend-boost',
  path: '/trend-boost',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralRoute = ReferralRouteImport.update({
  id: '/referral',
  path: '/referral',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptsRoute = PromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditsRoute = CreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateFromScratchRoute = CreateFromScratchRouteImport.update({
  id: '/create-from-scratch',
  path: '/create-from-scratch',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateAvatarRoute = CreateAvatarRouteImport.update({
  id: '/create-avatar',
  path: '/create-avatar',
  getParentRoute: () => rootRouteImport,
} as any)
const AvatarsRoute = AvatarsRouteImport.update({
  id: '/avatars',
  path: '/avatars',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendBoostIndexRoute = TrendBoostIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TrendBoostRoute,
} as any)
const TemplatesIndexRoute = TemplatesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TemplatesRoute,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudioRoute,
} as any)
const CreateFromScratchIndexRoute = CreateFromScratchIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CreateFromScratchRoute,
} as any)
const TrendBoostTemplateRoute = TrendBoostTemplateRouteImport.update({
  id: '/$template',
  path: '/$template',
  getParentRoute: () => TrendBoostRoute,
} as any)
const TemplatesUseRoute = TemplatesUseRouteImport.update({
  id: '/use',
  path: '/use',
  getParentRoute: () => TemplatesRoute,
} as any)
const StudioFormatRoute = StudioFormatRouteImport.update({
  id: '/$format',
  path: '/$format',
  getParentRoute: () => StudioRoute,
} as any)
const GenerateViralTemplateRoute = GenerateViralTemplateRouteImport.update({
  id: '/generate/viral-template',
  path: '/generate/viral-template',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateFromScratchScenarioRoute =
  CreateFromScratchScenarioRouteImport.update({
    id: '/scenario',
    path: '/scenario',
    getParentRoute: () => CreateFromScratchRoute,
  } as any)
const CreateFromScratchPoseRoute = CreateFromScratchPoseRouteImport.update({
  id: '/pose',
  path: '/pose',
  getParentRoute: () => CreateFromScratchRoute,
} as any)
const TrendBoostTemplateIndexRoute = TrendBoostTemplateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TrendBoostTemplateRoute,
} as any)
const TrendBoostTemplateCharacterIdRoute =
  TrendBoostTemplateCharacterIdRouteImport.update({
    id: '/$characterId',
    path: '/$characterId',
    getParentRoute: () => TrendBoostTemplateRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/avatars': typeof AvatarsRoute
  '/create-avatar': typeof CreateAvatarRoute
  '/create-from-scratch': typeof CreateFromScratchRouteWithChildren
  '/credits': typeof CreditsRoute
  '/dashboard': typeof DashboardRoute
  '/editor': typeof EditorRoute
  '/login': typeof LoginRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/prompts': typeof PromptsRoute
  '/referral': typeof ReferralRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio': typeof StudioRouteWithChildren
  '/templates': typeof TemplatesRouteWithChildren
  '/tools': typeof ToolsRoute
  '/trend-boost': typeof TrendBoostRouteWithChildren
  '/create-from-scratch/pose': typeof CreateFromScratchPoseRoute
  '/create-from-scratch/scenario': typeof CreateFromScratchScenarioRoute
  '/generate/viral-template': typeof GenerateViralTemplateRoute
  '/studio/$format': typeof StudioFormatRoute
  '/templates/use': typeof TemplatesUseRoute
  '/trend-boost/$template': typeof TrendBoostTemplateRouteWithChildren
  '/create-from-scratch/': typeof CreateFromScratchIndexRoute
  '/studio/': typeof StudioIndexRoute
  '/templates/': typeof TemplatesIndexRoute
  '/trend-boost/': typeof TrendBoostIndexRoute
  '/trend-boost/$template/$characterId': typeof TrendBoostTemplateCharacterIdRoute
  '/trend-boost/$template/': typeof TrendBoostTemplateIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/avatars': typeof AvatarsRoute
  '/create-avatar': typeof CreateAvatarRoute
  '/credits': typeof CreditsRoute
  '/dashboard': typeof DashboardRoute
  '/editor': typeof EditorRoute
  '/login': typeof LoginRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/prompts': typeof PromptsRoute
  '/referral': typeof ReferralRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tools': typeof ToolsRoute
  '/create-from-scratch/pose': typeof CreateFromScratchPoseRoute
  '/create-from-scratch/scenario': typeof CreateFromScratchScenarioRoute
  '/generate/viral-template': typeof GenerateViralTemplateRoute
  '/studio/$format': typeof StudioFormatRoute
  '/templates/use': typeof TemplatesUseRoute
  '/create-from-scratch': typeof CreateFromScratchIndexRoute
  '/studio': typeof StudioIndexRoute
  '/templates': typeof TemplatesIndexRoute
  '/trend-boost': typeof TrendBoostIndexRoute
  '/trend-boost/$template/$characterId': typeof TrendBoostTemplateCharacterIdRoute
  '/trend-boost/$template': typeof TrendBoostTemplateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/avatars': typeof AvatarsRoute
  '/create-avatar': typeof CreateAvatarRoute
  '/create-from-scratch': typeof CreateFromScratchRouteWithChildren
  '/credits': typeof CreditsRoute
  '/dashboard': typeof DashboardRoute
  '/editor': typeof EditorRoute
  '/login': typeof LoginRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/prompts': typeof PromptsRoute
  '/referral': typeof ReferralRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio': typeof StudioRouteWithChildren
  '/templates': typeof TemplatesRouteWithChildren
  '/tools': typeof ToolsRoute
  '/trend-boost': typeof TrendBoostRouteWithChildren
  '/create-from-scratch/pose': typeof CreateFromScratchPoseRoute
  '/create-from-scratch/scenario': typeof CreateFromScratchScenarioRoute
  '/generate/viral-template': typeof GenerateViralTemplateRoute
  '/studio/$format': typeof StudioFormatRoute
  '/templates/use': typeof TemplatesUseRoute
  '/trend-boost/$template': typeof TrendBoostTemplateRouteWithChildren
  '/create-from-scratch/': typeof CreateFromScratchIndexRoute
  '/studio/': typeof StudioIndexRoute
  '/templates/': typeof TemplatesIndexRoute
  '/trend-boost/': typeof TrendBoostIndexRoute
  '/trend-boost/$template/$characterId': typeof TrendBoostTemplateCharacterIdRoute
  '/trend-boost/$template/': typeof TrendBoostTemplateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/avatars'
    | '/create-avatar'
    | '/create-from-scratch'
    | '/credits'
    | '/dashboard'
    | '/editor'
    | '/login'
    | '/products'
    | '/profile'
    | '/prompts'
    | '/referral'
    | '/register'
    | '/settings'
    | '/sitemap.xml'
    | '/studio'
    | '/templates'
    | '/tools'
    | '/trend-boost'
    | '/create-from-scratch/pose'
    | '/create-from-scratch/scenario'
    | '/generate/viral-template'
    | '/studio/$format'
    | '/templates/use'
    | '/trend-boost/$template'
    | '/create-from-scratch/'
    | '/studio/'
    | '/templates/'
    | '/trend-boost/'
    | '/trend-boost/$template/$characterId'
    | '/trend-boost/$template/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/avatars'
    | '/create-avatar'
    | '/credits'
    | '/dashboard'
    | '/editor'
    | '/login'
    | '/products'
    | '/profile'
    | '/prompts'
    | '/referral'
    | '/register'
    | '/settings'
    | '/sitemap.xml'
    | '/tools'
    | '/create-from-scratch/pose'
    | '/create-from-scratch/scenario'
    | '/generate/viral-template'
    | '/studio/$format'
    | '/templates/use'
    | '/create-from-scratch'
    | '/studio'
    | '/templates'
    | '/trend-boost'
    | '/trend-boost/$template/$characterId'
    | '/trend-boost/$template'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/avatars'
    | '/create-avatar'
    | '/create-from-scratch'
    | '/credits'
    | '/dashboard'
    | '/editor'
    | '/login'
    | '/products'
    | '/profile'
    | '/prompts'
    | '/referral'
    | '/register'
    | '/settings'
    | '/sitemap.xml'
    | '/studio'
    | '/templates'
    | '/tools'
    | '/trend-boost'
    | '/create-from-scratch/pose'
    | '/create-from-scratch/scenario'
    | '/generate/viral-template'
    | '/studio/$format'
    | '/templates/use'
    | '/trend-boost/$template'
    | '/create-from-scratch/'
    | '/studio/'
    | '/templates/'
    | '/trend-boost/'
    | '/trend-boost/$template/$characterId'
    | '/trend-boost/$template/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AvatarsRoute: typeof AvatarsRoute
  CreateAvatarRoute: typeof CreateAvatarRoute
  CreateFromScratchRoute: typeof CreateFromScratchRouteWithChildren
  CreditsRoute: typeof CreditsRoute
  DashboardRoute: typeof DashboardRoute
  EditorRoute: typeof EditorRoute
  LoginRoute: typeof LoginRoute
  ProductsRoute: typeof ProductsRoute
  ProfileRoute: typeof ProfileRoute
  PromptsRoute: typeof PromptsRoute
  ReferralRoute: typeof ReferralRoute
  RegisterRoute: typeof RegisterRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StudioRoute: typeof StudioRouteWithChildren
  TemplatesRoute: typeof TemplatesRouteWithChildren
  ToolsRoute: typeof ToolsRoute
  TrendBoostRoute: typeof TrendBoostRouteWithChildren
  GenerateViralTemplateRoute: typeof GenerateViralTemplateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trend-boost': {
      id: '/trend-boost'
      path: '/trend-boost'
      fullPath: '/trend-boost'
      preLoaderRoute: typeof TrendBoostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referral': {
      id: '/referral'
      path: '/referral'
      fullPath: '/referral'
      preLoaderRoute: typeof ReferralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompts': {
      id: '/prompts'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof PromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credits': {
      id: '/credits'
      path: '/credits'
      fullPath: '/credits'
      preLoaderRoute: typeof CreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-from-scratch': {
      id: '/create-from-scratch'
      path: '/create-from-scratch'
      fullPath: '/create-from-scratch'
      preLoaderRoute: typeof CreateFromScratchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-avatar': {
      id: '/create-avatar'
      path: '/create-avatar'
      fullPath: '/create-avatar'
      preLoaderRoute: typeof CreateAvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avatars': {
      id: '/avatars'
      path: '/avatars'
      fullPath: '/avatars'
      preLoaderRoute: typeof AvatarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trend-boost/': {
      id: '/trend-boost/'
      path: '/'
      fullPath: '/trend-boost/'
      preLoaderRoute: typeof TrendBoostIndexRouteImport
      parentRoute: typeof TrendBoostRoute
    }
    '/templates/': {
      id: '/templates/'
      path: '/'
      fullPath: '/templates/'
      preLoaderRoute: typeof TemplatesIndexRouteImport
      parentRoute: typeof TemplatesRoute
    }
    '/studio/': {
      id: '/studio/'
      path: '/'
      fullPath: '/studio/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof StudioRoute
    }
    '/create-from-scratch/': {
      id: '/create-from-scratch/'
      path: '/'
      fullPath: '/create-from-scratch/'
      preLoaderRoute: typeof CreateFromScratchIndexRouteImport
      parentRoute: typeof CreateFromScratchRoute
    }
    '/trend-boost/$template': {
      id: '/trend-boost/$template'
      path: '/$template'
      fullPath: '/trend-boost/$template'
      preLoaderRoute: typeof TrendBoostTemplateRouteImport
      parentRoute: typeof TrendBoostRoute
    }
    '/templates/use': {
      id: '/templates/use'
      path: '/use'
      fullPath: '/templates/use'
      preLoaderRoute: typeof TemplatesUseRouteImport
      parentRoute: typeof TemplatesRoute
    }
    '/studio/$format': {
      id: '/studio/$format'
      path: '/$format'
      fullPath: '/studio/$format'
      preLoaderRoute: typeof StudioFormatRouteImport
      parentRoute: typeof StudioRoute
    }
    '/generate/viral-template': {
      id: '/generate/viral-template'
      path: '/generate/viral-template'
      fullPath: '/generate/viral-template'
      preLoaderRoute: typeof GenerateViralTemplateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-from-scratch/scenario': {
      id: '/create-from-scratch/scenario'
      path: '/scenario'
      fullPath: '/create-from-scratch/scenario'
      preLoaderRoute: typeof CreateFromScratchScenarioRouteImport
      parentRoute: typeof CreateFromScratchRoute
    }
    '/create-from-scratch/pose': {
      id: '/create-from-scratch/pose'
      path: '/pose'
      fullPath: '/create-from-scratch/pose'
      preLoaderRoute: typeof CreateFromScratchPoseRouteImport
      parentRoute: typeof CreateFromScratchRoute
    }
    '/trend-boost/$template/': {
      id: '/trend-boost/$template/'
      path: '/'
      fullPath: '/trend-boost/$template/'
      preLoaderRoute: typeof TrendBoostTemplateIndexRouteImport
      parentRoute: typeof TrendBoostTemplateRoute
    }
    '/trend-boost/$template/$characterId': {
      id: '/trend-boost/$template/$characterId'
      path: '/$characterId'
      fullPath: '/trend-boost/$template/$characterId'
      preLoaderRoute: typeof TrendBoostTemplateCharacterIdRouteImport
      parentRoute: typeof TrendBoostTemplateRoute
    }
  }
}

interface CreateFromScratchRouteChildren {
  CreateFromScratchPoseRoute: typeof CreateFromScratchPoseRoute
  CreateFromScratchScenarioRoute: typeof CreateFromScratchScenarioRoute
  CreateFromScratchIndexRoute: typeof CreateFromScratchIndexRoute
}

const CreateFromScratchRouteChildren: CreateFromScratchRouteChildren = {
  CreateFromScratchPoseRoute: CreateFromScratchPoseRoute,
  CreateFromScratchScenarioRoute: CreateFromScratchScenarioRoute,
  CreateFromScratchIndexRoute: CreateFromScratchIndexRoute,
}

const CreateFromScratchRouteWithChildren =
  CreateFromScratchRoute._addFileChildren(CreateFromScratchRouteChildren)

interface StudioRouteChildren {
  StudioFormatRoute: typeof StudioFormatRoute
  StudioIndexRoute: typeof StudioIndexRoute
}

const StudioRouteChildren: StudioRouteChildren = {
  StudioFormatRoute: StudioFormatRoute,
  StudioIndexRoute: StudioIndexRoute,
}

const StudioRouteWithChildren =
  StudioRoute._addFileChildren(StudioRouteChildren)

interface TemplatesRouteChildren {
  TemplatesUseRoute: typeof TemplatesUseRoute
  TemplatesIndexRoute: typeof TemplatesIndexRoute
}

const TemplatesRouteChildren: TemplatesRouteChildren = {
  TemplatesUseRoute: TemplatesUseRoute,
  TemplatesIndexRoute: TemplatesIndexRoute,
}

const TemplatesRouteWithChildren = TemplatesRoute._addFileChildren(
  TemplatesRouteChildren,
)

interface TrendBoostTemplateRouteChildren {
  TrendBoostTemplateCharacterIdRoute: typeof TrendBoostTemplateCharacterIdRoute
  TrendBoostTemplateIndexRoute: typeof TrendBoostTemplateIndexRoute
}

const TrendBoostTemplateRouteChildren: TrendBoostTemplateRouteChildren = {
  TrendBoostTemplateCharacterIdRoute: TrendBoostTemplateCharacterIdRoute,
  TrendBoostTemplateIndexRoute: TrendBoostTemplateIndexRoute,
}

const TrendBoostTemplateRouteWithChildren =
  TrendBoostTemplateRoute._addFileChildren(TrendBoostTemplateRouteChildren)

interface TrendBoostRouteChildren {
  TrendBoostTemplateRoute: typeof TrendBoostTemplateRouteWithChildren
  TrendBoostIndexRoute: typeof TrendBoostIndexRoute
}

const TrendBoostRouteChildren: TrendBoostRouteChildren = {
  TrendBoostTemplateRoute: TrendBoostTemplateRouteWithChildren,
  TrendBoostIndexRoute: TrendBoostIndexRoute,
}

const TrendBoostRouteWithChildren = TrendBoostRoute._addFileChildren(
  TrendBoostRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AvatarsRoute: AvatarsRoute,
  CreateAvatarRoute: CreateAvatarRoute,
  CreateFromScratchRoute: CreateFromScratchRouteWithChildren,
  CreditsRoute: CreditsRoute,
  DashboardRoute: DashboardRoute,
  EditorRoute: EditorRoute,
  LoginRoute: LoginRoute,
  ProductsRoute: ProductsRoute,
  ProfileRoute: ProfileRoute,
  PromptsRoute: PromptsRoute,
  ReferralRoute: ReferralRoute,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StudioRoute: StudioRouteWithChildren,
  TemplatesRoute: TemplatesRouteWithChildren,
  ToolsRoute: ToolsRoute,
  TrendBoostRoute: TrendBoostRouteWithChildren,
  GenerateViralTemplateRoute: GenerateViralTemplateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
